// Generated by dts-bundle v0.4.3
// Dependencies for this module:
//   ../http
//   ../events
//   ../stream

declare module 'catro' {
    import * as http from 'http';
    import { EventEmitter } from 'events';
    import RequestHandler from 'catro/request';
    import { KeyCertPair } from 'catro/utils/cert';
    import { Headers, Request, Response } from 'catro/typed';
    export interface Options {
        port: number;
        certPath: string;
        https?: {
            (host: string): boolean;
        } | boolean;
        rejectUnauthorized?: boolean;
        ca?: KeyCertPair;
        openssl?: string;
    }
    export default class Proxy extends EventEmitter {
        httpServer: http.Server;
        constructor(options: Options);
        /**
          * Any error on start can be catched here.
          */
        start(): Promise<this>;
        CACertPath: string;
    }
    export { Headers, Request, Response };
    export type RequestHandler = RequestHandler;
}

declare module 'catro/request' {
    import * as http from 'http';
    import { EventEmitter } from 'events';
    import CertManager from 'catro/utils/cert';
    import { Request, Response, Logger } from 'catro/typed';
    export interface RequestHandlerOptions {
        protocol: string;
        req: http.IncomingMessage;
        res: http.ServerResponse;
        rejectUnauthorized: boolean;
        certManager: CertManager;
        logger: Logger;
    }
    export default class RequestHandler extends EventEmitter {
        protocol: string;
        req: http.IncomingMessage;
        res: http.ServerResponse;
        replaceRequest: (request: Request, requestHandler?: this) => Promise<Request> | Request;
        replaceResponse: (request: Response, requestHandler?: this) => Promise<Response> | Response;
        request: Request;
        response: Response;
        constructor(options: RequestHandlerOptions);
        preventRequest(): void;
        url: string;
    }
}

declare module 'catro/utils/cert' {
    import { Logger } from 'catro/typed';
    export interface KeyCertPair {
        key: Buffer;
        cert: Buffer;
    }
    export interface CertManagerOptions {
        rootPath: string;
        logger: Logger;
        customCA?: KeyCertPair;
        opensslPath?: string;
    }
    export default class CertManager {
        rootPath: string;
        logger: Logger;
        customCA: KeyCertPair;
        opensslPath: string;
        constructor(options: CertManagerOptions);
        init(): Promise<void>;
        CAKeyPath: string;
        CACertPath: string;
        readCerts(domain: string): Promise<{
            key: Buffer;
            cert: Buffer;
        }>;
        CAExist(): Promise<boolean>;
        getCerts(domain: string): Promise<KeyCertPair>;
    }
}

declare module 'catro/typed' {
    import { Readable } from 'stream';
    export interface Headers {
        [key: string]: string;
    }
    /**
      * Request is a superset of <http.requestOptions>
      */
    export interface Request {
        method: string;
        hostname: string;
        port: string;
        path: string;
        headers: Headers;
        body: Readable | string | Buffer;
    }
    export interface Response {
        status: number;
        headers: Headers;
        body: Readable | string | Buffer;
    }
    export interface Logger {
        info(...args: any[]): any;
        error(...args: any[]): any;
        warn(...args: any[]): any;
    }
    export interface LoggerFactory {
        (name: string): Logger;
    }
}
